insert into public.menu_items
  (id, category, type, name, description, price, image_url, minimum_quantity, is_available, sort_order)
values
  ('poke-salmon', '포케', 'picnic', '연어 포케', '신선한 연어를 올린 소풍 대표 포케', 15000, '/images/menu/poke-salmon.jpg', 1, true, 10),
  ('poke-pork-neck', '포케', 'picnic', '목살 포케', '든든하게 즐기는 목살 포케', 12000, '/images/menu/poke-pork-neck.jpg', 1, true, 20),
  ('poke-shrimp', '포케', 'picnic', '새우 포케', '탱글한 새우를 담은 산뜻한 포케', 12000, '/images/menu/poke-shrimp.jpg', 1, true, 30),
  ('poke-bulgogi', '포케', 'picnic', '불고기 포케', '달콤짭짤한 불고기를 담은 포케', 12000, '/images/menu/poke-bulgogi.jpg', 1, true, 40),
  ('poke-chicken-breast', '포케', 'picnic', '닭가슴살 포케', '가볍고 균형 잡힌 닭가슴살 포케', 12000, '/images/menu/poke-chicken-breast.jpg', 1, true, 50),
  ('coffee-hand-drip-hot', '커피', 'picnic', '핸드드립 hot', '따뜻하게 즐기는 핸드드립 커피', 4000, '/images/menu/coffee-hand-drip-hot.jpg', 1, true, 60),
  ('coffee-hand-drip-iced', '커피', 'picnic', '핸드드립 iced', '차갑게 즐기는 핸드드립 커피', 4500, '/images/menu/coffee-hand-drip-iced.jpg', 1, true, 70),
  ('coffee-cafe-au-lait-iced', '커피', 'picnic', '카페오레', '아이스 전용 카페오레', 4800, '/images/menu/coffee-cafe-au-lait-iced.jpg', 1, true, 80),
  ('coffee-mixcream-latte-iced', '커피', 'picnic', '믹스크림라떼', '아이스 전용 믹스크림라떼', 4500, '/images/menu/coffee-mixcream-latte-iced.jpg', 1, true, 90),
  ('tea-orange-icecream', '블렌딩 티', 'picnic', '오렌지 아이스크림', '과일이 통째로 들어간 과일 블렌딩 티로 오렌지의 쥬시함이 그대로 느껴지는 과일 허브차', 4500, '/images/menu/tea-orange-icecream.jpg', 1, true, 100),
  ('tea-flower-garden', '블렌딩 티', 'picnic', '플라워가든', '봄향기 가득한 정원에서 꽃잎을 정성스레 따온 듯한 향긋한 과일 블렌드티', 4500, '/images/menu/tea-flower-garden.jpg', 1, true, 110),
  ('tea-pink-grapefruit-blossom', '블렌딩 티', 'picnic', '핑크자몽블라썸', '레몬그라스의 은은한 레몬향과 자몽에서 주는 신선함과 상큼함이 블렌딩된 자몽허브티', 4500, '/images/menu/tea-pink-grapefruit-blossom.jpg', 1, true, 120),
  ('tea-chamomile', '허브차', 'picnic', '캐모마일', '사과같은 캐모마일 향이 은은하게 풍기면서 캐모마일 자체의 순수한 단맛이 느껴지는 꽃차', 3500, '/images/menu/tea-chamomile.jpg', 1, true, 130),
  ('tea-mint', '허브차', 'picnic', '민트', '페퍼민트와 레몬그라스의 완벽한 조합, 입안 가득 상쾌함이 느껴지는 허브차', 3500, '/images/menu/tea-mint.jpg', 1, true, 140),
  ('tea-hibiscus', '허브차', 'picnic', '히비스커스', '루비와 같은 붉은 수색에 히비스커스의 강렬한 신맛과 순수 단맛이 느껴지는 허브차', 3500, '/images/menu/tea-hibiscus.jpg', 1, true, 150),
  ('tea-mix-berry', '블렌딩 티', 'picnic', '믹스베리', '상큼한 사우어 라즈베리티에 세 가지 베리청이 어우러진 진하게 즐기는 과일 블렌딩티', 5000, '/images/menu/tea-mix-berry.jpg', 1, true, 160),
  ('tea-peach-and-lychee', '블렌딩 티', 'picnic', '피치 앤 리치', '잘 익은 복숭아의 부드러운 달콤함에 리치의 은은하고 이국적인 향을 더한 과일 블렌딩티', 5000, '/images/menu/tea-peach-and-lychee.jpg', 1, true, 170),
  ('tea-green-mint', '블렌딩 티', 'picnic', '그린민트', '민트티의 깔끔한 향과 청사과의 상큼한 달콤함이 입 안을 산뜻하게 깨워주는 청량 과일티', 5000, '/images/menu/tea-green-mint.jpg', 1, true, 180),
  ('latte-matcha-strawberry', '라떼', 'picnic', '말차딸기라떼', '슈퍼말차의 은은한 쌉쌀함에 수제 딸기청의 달콤함이 더해져 부드럽게 어우러지는 조화로운 라떼', 6000, '/images/menu/latte-matcha-strawberry.jpg', 1, true, 190),
  ('latte-matcha', '라떼', 'picnic', '말차라떼', '프리미엄 슈퍼말차를 사용해 말차 본연의 은은한 쌉쌀함과 고소한 우유가 조화로운 말차라떼', 5000, '/images/menu/latte-matcha.jpg', 1, true, 200),
  ('latte-strawberry', '라떼', 'picnic', '딸기라떼', '정성껏 만든 수제 딸기청을 담아 우유와 부드럽게 어우러진 클래식한 딸기라떼', 5000, '/images/menu/latte-strawberry.jpg', 1, true, 210),
  ('latte-chocolate', '라떼', 'picnic', '초코라떼', '부드럽고 달콤하게 즐기는 초코라떼', 4000, '/images/menu/latte-chocolate.jpg', 1, true, 220),
  ('ade-grapefruit', '에이드', 'picnic', '자몽에이드', '상큼한 자몽에이드', 4500, '/images/menu/ade-grapefruit.jpg', 1, true, 230),
  ('ade-lemon', '에이드', 'picnic', '레몬에이드', '청량하게 즐기는 레몬에이드', 4500, '/images/menu/ade-lemon.jpg', 1, true, 240),
  ('ade-green-grape', '에이드', 'picnic', '청포도에이드', '달콤하고 산뜻한 청포도에이드', 4500, '/images/menu/ade-green-grape.jpg', 1, true, 250),
  ('ade-plum', '에이드', 'picnic', '자두에이드', '자두의 새콤달콤함을 담은 에이드', 4500, '/images/menu/ade-plum.jpg', 1, true, 260),
  ('dessert-mochi', '디저트', 'picnic', '모찌', '망고, 딸기요거트, 녹차, 라즈베리, 민트초코', 4000, '/images/menu/dessert-mochi.jpg', 1, true, 270),
  ('dessert-plain-scone', '디저트', 'picnic', '플레인 스콘', '담백하게 즐기는 플레인 스콘', 3500, '/images/menu/dessert-plain-scone.jpg', 1, true, 280),
  ('dessert-matcha-scone', '디저트', 'picnic', '말차 스콘', '말차 향을 더한 스콘', 3800, '/images/menu/dessert-matcha-scone.jpg', 1, true, 290),
  ('dessert-plain-financier', '디저트', 'picnic', '플레인 휘낭시에', '고소하고 촉촉한 플레인 휘낭시에', 2800, '/images/menu/dessert-plain-financier.jpg', 1, true, 300)
on conflict (id) do update set
  category = excluded.category,
  type = excluded.type,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image_url = excluded.image_url,
  minimum_quantity = excluded.minimum_quantity,
  is_available = excluded.is_available,
  sort_order = excluded.sort_order,
  updated_at = now();
